"""Leitura estrutural do subconjunto TMDL usado pelo LeitorBI.

O parser é deliberadamente pequeno, mas não usa uma expressão regular para
interpretar o documento inteiro. Primeiro transforma linhas e blocos fenced em
uma árvore de nós baseada na indentação; só depois normaliza os nós relevantes
para o mesmo contrato canônico usado pelo reader TMSL.
"""

from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from fastapi import HTTPException

from app.diagnostics.events import record_event


HEADER_RE = re.compile(r"^(model|table|column|measure|partition|relationship)\b(.*)$", re.IGNORECASE)
PROPERTY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$")
ASSIGNMENT_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")
SUPPORTED_HEADERS = {"model", "table", "column", "measure", "partition", "relationship"}
MODEL_PROPERTIES = {"culture", "defaultMode", "storageMode"}
TABLE_PROPERTIES = {"description", "isHidden", "isAutoGenerated", "tableType", "type"}
COLUMN_PROPERTIES = {"dataType", "columnType", "description", "isHidden", "formatString", "displayFolder", "dataCategory", "expression"}
MEASURE_PROPERTIES = {"description", "isHidden", "formatString", "displayFolder", "expression"}
PARTITION_PROPERTIES = {"mode", "source", "expression", "query"}
RELATIONSHIP_PROPERTIES = {
    "fromTable", "fromColumn", "toTable", "toColumn", "fromCardinality",
    "toCardinality", "crossFilteringBehavior", "isActive",
}


@dataclass
class TmdlLine:
    number: int
    indent: int
    text: str
    block_value: str | None = None


@dataclass
class TmdlNode:
    kind: str
    name: str
    line: int
    indent: int
    header_value: str = ""
    properties: dict[str, str] = field(default_factory=dict)
    children: list["TmdlNode"] = field(default_factory=list)


def _error(message: str, line: int | None = None) -> HTTPException:
    suffix = f" na linha {line}" if line is not None else ""
    return HTTPException(status_code=422, detail=f"TMDL inválido{suffix}: {message}")


def _indent_of(raw: str) -> int:
    indent = 0
    for char in raw:
        if char == " ":
            indent += 1
        elif char == "\t":
            indent += 4
        else:
            break
    return indent


def _strip_comment(text: str) -> str:
    stripped = text.strip()
    if stripped.startswith("//"):
        return ""
    return stripped


def _dedent_block(lines: list[str]) -> str:
    if not lines:
        return ""
    return textwrap.dedent("\n".join(lines)).strip()


def _consume_fenced(raw_text: str, physical_lines: list[str], index: int, line_number: int) -> tuple[str, int, str]:
    fence_position = raw_text.find("```")
    prefix = raw_text[:fence_position].rstrip()
    remainder = raw_text[fence_position + 3 :]
    block_lines: list[str] = []
    closing = remainder.find("```")
    if closing >= 0:
        block_lines.append(remainder[:closing])
        return prefix, index, _dedent_block(block_lines)

    if remainder:
        block_lines.append(remainder)
    cursor = index + 1
    while cursor < len(physical_lines):
        current = physical_lines[cursor]
        close_position = current.find("```")
        if close_position >= 0:
            block_lines.append(current[:close_position])
            return prefix, cursor, _dedent_block(block_lines)
        block_lines.append(current)
        cursor += 1
    raise _error("bloco multilinha aberto sem fechamento.", line_number)


def _tokenize(content: bytes, path: str) -> list[TmdlLine]:
    try:
        text = content.decode("utf-8-sig")
    except UnicodeDecodeError as exc:
        raise _error(f"o arquivo {path} precisa estar em UTF-8.") from exc

    physical_lines = text.splitlines()
    tokens: list[TmdlLine] = []
    index = 0
    while index < len(physical_lines):
        raw = physical_lines[index]
        number = index + 1
        indent = _indent_of(raw)
        logical = _strip_comment(raw)
        if not logical:
            index += 1
            continue
        block_value: str | None = None
        if "```" in logical:
            logical, consumed_index, block_value = _consume_fenced(logical, physical_lines, index, number)
            index = consumed_index
        logical = logical.strip()
        if not logical:
            raise _error("declaração vazia antes de um bloco multilinha.", number)
        tokens.append(TmdlLine(number=number, indent=indent, text=logical, block_value=block_value))
        index += 1
    return tokens


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == "'":
        cursor = 1
        while cursor < len(value):
            if value[cursor] == "'":
                if cursor + 1 < len(value) and value[cursor + 1] == "'":
                    cursor += 2
                    continue
                if cursor == len(value) - 1:
                    return value[1:-1].replace("''", "'")
                break
            cursor += 1
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        return value[1:-1].replace('\\"', '"')
    return value


def _identifier(rest: str, line: int) -> tuple[str, str]:
    rest = rest.strip()
    if not rest:
        raise _error("entidade sem nome.", line)
    if rest.startswith("'"):
        cursor = 1
        while cursor < len(rest):
            if rest[cursor] == "'":
                if cursor + 1 < len(rest) and rest[cursor + 1] == "'":
                    cursor += 2
                    continue
                return _unquote(rest[: cursor + 1]), rest[cursor + 1 :].strip()
            cursor += 1
        raise _error("identificador entre aspas simples não foi fechado.", line)
    match = re.match(r"([^\s=]+)(.*)$", rest)
    if not match:
        raise _error("entidade sem nome.", line)
    return _unquote(match.group(1)), match.group(2).strip()


def _parse_header(token: TmdlLine) -> TmdlNode | None:
    match = HEADER_RE.match(token.text)
    if not match:
        return None
    kind = match.group(1).lower()
    name, remainder = _identifier(match.group(2), token.number)
    header_value = ""
    if remainder:
        if not remainder.startswith("="):
            if kind in SUPPORTED_HEADERS:
                raise _error(f"declaração de {kind} contém sintaxe não reconhecida.", token.number)
        else:
            header_value = remainder[1:].strip()
    if token.block_value is not None:
        header_value = token.block_value
    return TmdlNode(
        kind=kind,
        name=name,
        line=token.number,
        indent=token.indent,
        header_value=header_value,
    )


def _parse_property(token: TmdlLine) -> tuple[str, str] | None:
    match = PROPERTY_RE.match(token.text)
    if not match:
        match = ASSIGNMENT_RE.match(token.text)
    if not match:
        return None
    value = token.block_value if token.block_value is not None else match.group(2).strip()
    return match.group(1), _unquote(value)


def _parse_document(content: bytes, path: str) -> list[TmdlNode]:
    tokens = _tokenize(content, path)
    roots: list[TmdlNode] = []
    stack: list[TmdlNode] = []
    for token in tokens:
        while stack and token.indent <= stack[-1].indent:
            stack.pop()
        property_item = _parse_property(token)
        if property_item is not None:
            if not stack:
                raise _error("propriedade fora de uma entidade.", token.number)
            key, value = property_item
            stack[-1].properties[key] = value
            continue

        node = _parse_header(token)
        if node is None:
            # TMDL contains many metadata blocks that are intentionally outside
            # this product's canonical model. They are ignored as long as they
            # remain structurally nested under a known entity.
            if not stack:
                continue
            continue

        if stack:
            stack[-1].children.append(node)
        else:
            roots.append(node)
        stack.append(node)
    return roots


def _nodes(roots: Iterable[TmdlNode], kind: str) -> list[TmdlNode]:
    result: list[TmdlNode] = []
    for node in roots:
        if node.kind == kind:
            result.append(node)
        result.extend(_nodes(node.children, kind))
    return result


def _property(node: TmdlNode, key: str, default: str = "") -> str:
    return node.properties.get(key, default)


def _bool(value: str, default: bool = False) -> bool:
    if not value:
        return default
    return value.strip().lower() in {"true", "1", "yes", "sim"}


def _enum(value: str) -> str:
    values = {
        "many": "Many",
        "one": "One",
        "none": "None",
        "onedirection": "OneDirection",
        "bothdirections": "BothDirections",
        "automatic": "Automatic",
        "import": "import",
        "directquery": "directQuery",
        "dual": "dual",
    }
    return values.get(value.strip().lower(), value.strip())


def _model_type(value: str, default: str) -> str:
    values = {
        "regular": "Regular",
        "calculated": "CalculatedTable",
        "calculatedtable": "CalculatedTable",
        "datacolumn": "DataColumn",
        "calculatedcolumn": "CalculatedColumn",
    }
    return values.get(value.strip().lower(), value.strip() or default)


def _reference(value: str) -> tuple[str, str]:
    value = value.strip()
    if "." not in value:
        return "", _unquote(value)
    table, column = value.rsplit(".", 1)
    return _unquote(table.strip()), _unquote(column.strip())


def _canonical_column(node: TmdlNode) -> dict[str, Any]:
    expression = _property(node, "expression", node.header_value)
    column_type = _model_type(_property(node, "columnType"), "CalculatedColumn" if expression else "DataColumn")
    return {
        "name": node.name,
        "dataType": _property(node, "dataType"),
        "columnType": column_type,
        "isHidden": _bool(_property(node, "isHidden")),
        "formatString": _property(node, "formatString"),
        "dataCategory": _property(node, "dataCategory"),
        "displayFolder": _property(node, "displayFolder"),
        "description": _property(node, "description"),
    }


def _canonical_measure(node: TmdlNode) -> dict[str, Any]:
    expression = _property(node, "expression", node.header_value)
    return {
        "name": node.name,
        "expression": expression,
        "isHidden": _bool(_property(node, "isHidden")),
        "formatString": _property(node, "formatString"),
        "displayFolder": _property(node, "displayFolder"),
        "description": _property(node, "description"),
    }


def _canonical_partition(node: TmdlNode) -> dict[str, Any]:
    expression = _property(node, "source") or _property(node, "expression") or _property(node, "query")
    return {
        "name": node.name,
        "sourceType": _enum(node.header_value),
        "mode": _enum(_property(node, "mode")),
        "expression": expression,
    }


def _canonical_table(node: TmdlNode) -> dict[str, Any]:
    columns = [child for child in node.children if child.kind == "column"]
    measures = [child for child in node.children if child.kind == "measure"]
    partitions = [child for child in node.children if child.kind == "partition"]
    return {
        "name": node.name,
        "tableType": _model_type(_property(node, "tableType") or _property(node, "type"), "Regular"),
        "isHidden": _bool(_property(node, "isHidden")),
        "isAutoGenerated": _bool(_property(node, "isAutoGenerated")),
        "description": _property(node, "description"),
        "columns": [_canonical_column(column) for column in columns],
        "measures": [_canonical_measure(measure) for measure in measures],
        "partitions": [_canonical_partition(partition) for partition in partitions],
    }


def _canonical_relationship(node: TmdlNode) -> dict[str, Any]:
    from_table = _property(node, "fromTable")
    from_column = _property(node, "fromColumn")
    to_table = _property(node, "toTable")
    to_column = _property(node, "toColumn")
    if not from_table or not from_column:
        from_table, from_column = _reference(from_column or from_table)
    if not to_table or not to_column:
        to_table, to_column = _reference(to_column or to_table)
    return {
        "name": node.name,
        "fromTable": from_table,
        "fromColumn": from_column,
        "toTable": to_table,
        "toColumn": to_column,
        "fromCardinality": _enum(_property(node, "fromCardinality")),
        "toCardinality": _enum(_property(node, "toCardinality")),
        "crossFilteringBehavior": _enum(_property(node, "crossFilteringBehavior")),
        "isActive": _bool(_property(node, "isActive"), True),
    }


def _validate_unique(items: list[dict[str, Any]], label: str) -> None:
    seen: set[str] = set()
    for item in items:
        name = str(item.get("name", "")).strip()
        if not name:
            raise _error(f"{label} sem nome.")
        key = name.casefold()
        if key in seen:
            raise _error(f"{label} duplicada: {name}.")
        seen.add(key)


def _validate_relationships(tables: list[dict[str, Any]], relationships: list[dict[str, Any]]) -> None:
    tables_by_name = {table["name"].casefold(): table for table in tables}
    for relationship in relationships:
        from_table = relationship["fromTable"]
        to_table = relationship["toTable"]
        if not from_table or not to_table or not relationship["fromColumn"] or not relationship["toColumn"]:
            raise _error(f"relacionamento incompleto: {relationship['name']}.")
        for table_name, column_name, side in (
            (from_table, relationship["fromColumn"], "origem"),
            (to_table, relationship["toColumn"], "destino"),
        ):
            table = tables_by_name.get(table_name.casefold())
            if table is None:
                raise _error(f"relacionamento {relationship['name']} referencia tabela inexistente ({table_name}).")
            if not any(column["name"].casefold() == column_name.casefold() for column in table["columns"]):
                raise _error(
                    f"relacionamento {relationship['name']} referencia coluna inexistente no lado {side} ({table_name}.{column_name})."
                )


def read_tmdl_model(files: Mapping[str, bytes], dashboard_name: str = "", model_name: str = "") -> dict[str, Any]:
    roots: list[TmdlNode] = []
    for path in sorted(files):
        roots.extend(_parse_document(files[path], path))

    model_nodes = [node for node in roots if node.kind == "model"]
    if len(model_nodes) != 1:
        raise _error("o projeto precisa conter exatamente uma declaração model.")
    model = model_nodes[0]
    table_nodes = [node for node in roots if node.kind == "table"]
    if not table_nodes:
        raise _error("nenhuma tabela encontrada no modelo.")

    tables = [_canonical_table(table) for table in table_nodes]
    _validate_unique(tables, "tabela")
    for table in tables:
        _validate_unique(table["columns"], f"coluna da tabela {table['name']}")
        _validate_unique(table["measures"], f"medida da tabela {table['name']}")
        _validate_unique(table["partitions"], f"partição da tabela {table['name']}")

    relationships = [_canonical_relationship(node) for node in _nodes(roots, "relationship")]
    _validate_unique(relationships, "relacionamento")
    _validate_relationships(tables, relationships)

    modes = {partition["mode"] for table in tables for partition in table["partitions"] if partition["mode"]}
    default_mode = _property(model, "defaultMode") or _property(model, "storageMode")
    if not default_mode and len(modes) == 1:
        default_mode = next(iter(modes))
    resolved_model_name = model.name or model_name
    canonical = {
        "dashboardName": dashboard_name or resolved_model_name,
        "modelName": resolved_model_name,
        "exportDate": "",
        "modelMetadata": {
            "culture": _property(model, "culture"),
            "defaultMode": _enum(default_mode),
        },
        "tables": tables,
        "relationships": relationships,
    }
    record_event(
        "tmdl_loaded",
        tables=len(tables),
        relationships=len(relationships),
        measures=sum(len(table["measures"]) for table in tables),
    )
    return canonical
