import json
from typing import Any

from fastapi import HTTPException

from app.diagnostics.events import record_event

def _value(source: Any, key: str, default: Any = "") -> Any:
    if not isinstance(source, dict):
        return default
    value = source.get(key, default)
    return default if value is None else value


def _list(source: Any, key: str) -> list[Any]:
    value = _value(source, key, [])
    return value if isinstance(value, list) else []


def _partition_source(partition: dict[str, Any]) -> tuple[str, str]:
    source = _value(partition, "source", {})
    if not isinstance(source, dict):
        return "", ""

    source_type = _value(source, "type", "")
    expression = _value(source, "expression", "")
    if not expression:
        expression = _value(source, "query", "")
    return str(source_type), str(expression)


def _column_type(column: dict[str, Any]) -> str:
    explicit_type = _value(column, "columnType", "")
    if explicit_type:
        return str(explicit_type)
    if _value(column, "type", "") and str(_value(column, "type", "")).lower() == "calculated":
        return "CalculatedColumn"
    if _value(column, "expression", ""):
        return "CalculatedColumn"
    return "DataColumn"


def _table_type(table: dict[str, Any]) -> str:
    explicit_type = _value(table, "tableType", "")
    if explicit_type:
        return str(explicit_type)
    if _value(table, "type", ""):
        return str(_value(table, "type", ""))
    return "Regular"


def _canonical_column(column: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": _value(column, "name", ""),
        "dataType": _value(column, "dataType", ""),
        "columnType": _column_type(column),
        "isHidden": _value(column, "isHidden", False),
        "formatString": _value(column, "formatString", ""),
        "dataCategory": _value(column, "dataCategory", ""),
        "displayFolder": _value(column, "displayFolder", ""),
        "description": _value(column, "description", ""),
    }


def _canonical_measure(measure: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": _value(measure, "name", ""),
        "expression": _value(measure, "expression", ""),
        "isHidden": _value(measure, "isHidden", False),
        "formatString": _value(measure, "formatString", ""),
        "displayFolder": _value(measure, "displayFolder", ""),
        "description": _value(measure, "description", ""),
    }


def _canonical_partition(partition: dict[str, Any]) -> dict[str, Any]:
    source_type, expression = _partition_source(partition)
    return {
        "name": _value(partition, "name", ""),
        "sourceType": source_type,
        "mode": _value(partition, "mode", ""),
        "expression": expression,
    }


def _canonical_table(table: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": _value(table, "name", ""),
        "tableType": _table_type(table),
        "isHidden": _value(table, "isHidden", False),
        "isAutoGenerated": _value(table, "isAutoGenerated", False),
        "description": _value(table, "description", ""),
        "columns": [_canonical_column(column) for column in _list(table, "columns") if isinstance(column, dict)],
        "measures": [_canonical_measure(measure) for measure in _list(table, "measures") if isinstance(measure, dict)],
        "partitions": [_canonical_partition(partition) for partition in _list(table, "partitions") if isinstance(partition, dict)],
    }


def _default_mode(model: dict[str, Any], tables: list[dict[str, Any]]) -> str:
    explicit_mode = _value(model, "defaultMode", "") or _value(model, "storageMode", "")
    if explicit_mode:
        return str(explicit_mode)

    modes = {
        str(_value(partition, "mode", ""))
        for table in tables
        for partition in _list(table, "partitions")
        if _value(partition, "mode", "")
    }
    return next(iter(modes)) if len(modes) == 1 else ""


def read_tmsl_model(content: bytes, dashboard_name: str = "", model_name: str = "") -> dict[str, Any]:
    try:
        data = json.loads(content.decode("utf-8-sig"))
    except UnicodeDecodeError as exc:
        raise HTTPException(status_code=422, detail="model.bim inválido: use um arquivo em UTF-8.") from exc
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=422,
            detail=f"model.bim inválido: verifique a sintaxe na linha {exc.lineno}, coluna {exc.colno}.",
        ) from exc

    if not isinstance(data, dict) or not isinstance(data.get("model"), dict):
        raise HTTPException(status_code=422, detail="model.bim incompatível: objeto 'model' ausente ou inválido.")

    model = data["model"]
    source_tables = _list(model, "tables")
    if not source_tables:
        raise HTTPException(status_code=422, detail="model.bim incompatível: nenhuma tabela encontrada no modelo.")

    tables = [_canonical_table(table) for table in source_tables if isinstance(table, dict)]
    relationships = [relationship for relationship in _list(model, "relationships") if isinstance(relationship, dict)]
    resolved_model_name = str(_value(data, "name", "")) or str(_value(model, "name", "")) or model_name

    canonical = {
        "dashboardName": dashboard_name or resolved_model_name,
        "modelName": resolved_model_name,
        "exportDate": "",
        "modelMetadata": {
            "culture": _value(model, "culture", ""),
            "defaultMode": _default_mode(model, tables),
        },
        "tables": tables,
        "relationships": relationships,
    }
    record_event("tmsl_loaded", tables=len(tables), relationships=len(relationships), measures=sum(len(table["measures"]) for table in tables))
    return canonical
