import re
from typing import Any


def safe_value(source: dict[str, Any], key: str, default: Any = "") -> Any:
    value = source.get(key, default) if isinstance(source, dict) else default
    return default if value is None else value


def safe_list(source: dict[str, Any], key: str) -> list[Any]:
    value = source.get(key, []) if isinstance(source, dict) else []
    return value if isinstance(value, list) else []


def safe_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def normalize_text(value: Any) -> str:
    return safe_text(value).strip().lower()


def translate_model_type(value: Any) -> str:
    mapping = {
        "calculatedtable": "Tabela calculada",
        "calculated": "Calculado",
        "regular": "Regular",
        "m": "Power Query / M",
        "import": "Importado",
        "directquery": "DirectQuery",
        "dual": "Dual",
        "calculatedcolumn": "Coluna calculada",
        "datacolumn": "Coluna de dados",
    }
    text = safe_text(value)
    return mapping.get(normalize_text(text), text)


def detect_sql_in_m_expression(expression: Any) -> str:
    text = safe_text(expression)
    patterns = [
        r"Query\s*=\s*\"([^\"]+)\"",
        r"Value\.NativeQuery\s*\([^,]+,\s*\"([^\"]+)\"",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.DOTALL)
        if match:
            return match.group(1).replace("#(lf)", "\n").replace("#(tab)", "\t")
    return ""


def detect_database_server(expression: Any) -> tuple[str, str]:
    text = safe_text(expression)
    match = re.search(r"Sql\.Database\(\s*\"([^\"]+)\"\s*,\s*\"([^\"]+)\"", text, flags=re.IGNORECASE)
    if match:
        return match.group(1), match.group(2)
    return "", ""


def detect_by_patterns(text: str, patterns: list[str]) -> bool:
    return any(pattern in text for pattern in patterns)


def display_source_type(value: Any) -> str:
    text = safe_text(value)
    normalized = normalize_text(text)
    if normalized in {"calculated", "calculatedtable", "calculated table", "calculated_table", "calculado"}:
        return "Calculada"
    return text


class PowerBIAnalyzer:
    def __init__(self, data: dict[str, Any]):
        self.data = data
        self.metadata = safe_value(data, "modelMetadata", {})
        self.tables = safe_list(data, "tables")
        self.relationships = safe_list(data, "relationships")
        self._cache: dict[str, Any] = {}

    def is_technical_date_table_name(self, table_name: Any) -> bool:
        name = normalize_text(table_name)
        return "localdatetable" in name or "datetabletemplate" in name

    def is_technical_date_table(self, table: dict[str, Any]) -> bool:
        return self.is_technical_date_table_name(safe_value(table, "name", ""))

    def tables_without_technical_dates(self) -> list[dict[str, Any]]:
        if "tables_without_dates" not in self._cache:
            self._cache["tables_without_dates"] = [
                table for table in self.tables if not self.is_technical_date_table(table)
            ]
        return self._cache["tables_without_dates"]

    def is_visible_physical_table(self, table: dict[str, Any]) -> bool:
        return not (
            self.is_technical_date_table(table)
            or safe_value(table, "isHidden", False)
            or safe_value(table, "isAutoGenerated", False)
        )

    def visible_physical_tables(self) -> list[dict[str, Any]]:
        if "visible_physical_tables" not in self._cache:
            self._cache["visible_physical_tables"] = [
                table for table in self.tables_without_technical_dates()
                if self.is_visible_physical_table(table)
            ]
        return self._cache["visible_physical_tables"]

    def count_visible_fields(self, tables: list[dict[str, Any]] | None = None) -> int:
        selected_tables = tables if tables is not None else self.tables_without_technical_dates()
        return sum(
            1
            for table in selected_tables
            for column in safe_list(table, "columns")
            if not safe_value(column, "isHidden", False)
        )

    def count_total_columns(self) -> int:
        return sum(len(safe_list(table, "columns")) for table in self.tables_without_technical_dates())

    def detect_source_type(self, expression: Any, source_type: Any) -> str:
        text = normalize_text(expression)
        source_type_norm = normalize_text(source_type)

        if "analysisservices.database" in text and "powerbi://" in text:
            return "Power BI Dataset"
        if "sql.database" in text and (
            "database.windows.net" in text
            or ".sql.azuresynapse.net" in text
            or ".sqlanalytics.net" in text
            or "synapse" in text
        ):
            return "Azure SQL / Synapse"
        if detect_by_patterns(text, ["databricks.catalogs", "databricks.contents"]):
            return "Databricks"
        if "snowflake.databases" in text:
            return "Snowflake"
        if "googlebigquery.database" in text:
            return "BigQuery"
        if "postgresql.database" in text:
            return "PostgreSQL"
        if "mysql.database" in text:
            return "MySQL"
        if "oracle.database" in text:
            return "Oracle"
        if "teradata.database" in text:
            return "Teradata"
        if detect_by_patterns(text, ["azurestorage.datalake", "azuredatalakestorage.contents"]):
            return "Azure Data Lake"
        if "azurestorage.blobs" in text:
            return "Azure Blob Storage"
        if "sapbusinesswarehouse.cubes" in text:
            return "SAP BW"
        if "saphana.database" in text:
            return "SAP HANA"
        if detect_by_patterns(text, ["onelake", "fabric", "lakehouse"]):
            return "Fabric / OneLake"
        if detect_by_patterns(text, ["salesforce.data", "salesforce.reports"]):
            return "Salesforce"
        if detect_by_patterns(text, ["commondataservice.database", "cds.entities", "dataverse"]):
            return "Dataverse"
        if "parquet.document" in text or ".parquet" in text:
            return "Parquet"
        if "xml.tables" in text or ".xml" in text:
            return "XML"
        if "pdf.tables" in text or ".pdf" in text:
            return "PDF"
        if "access.database" in text or ".accdb" in text or ".mdb" in text:
            return "Access"
        if detect_by_patterns(text, ["odbc.datasource", "odbc.query"]):
            return "ODBC"
        if "oledb.datasource" in text:
            return "OLE DB"
        if "exchange.contents" in text:
            return "Exchange"
        if "docs.google.com/spreadsheets" in text or "google.com/spreadsheets" in text:
            return "Google Sheets"
        if detect_by_patterns(text, ["onedrive.live.com", "my.sharepoint.com/personal"]):
            return "OneDrive"
        if "sql.database" in text or (source_type_norm == "m" and "select " in text):
            return "SQL"
        if "excel.workbook" in text or ".xlsx" in text or ".xls" in text:
            return "Excel"
        if "sharepoint.files" in text or "sharepoint.contents" in text:
            return "SharePoint"
        if "web.contents" in text:
            return "Web"
        if "csv.document" in text or ".csv" in text:
            return "CSV"
        if "json.document" in text or ".json" in text:
            return "JSON"
        if "odata.feed" in text:
            return "OData"
        if "analysisservices.database" in text:
            return "Analysis Services"
        if "powerbi.dataflows" in text:
            return "Dataflow"
        if "folder.files" in text or "folder.contents" in text:
            return "Pasta"
        if source_type:
            return safe_text(source_type).upper()
        return "Nao identificado"

    def count_source_types(self, only_physical_tables: bool = False) -> dict[str, int]:
        cache_key = f"source_types:{only_physical_tables}"
        if cache_key in self._cache:
            return self._cache[cache_key]

        source_types: dict[str, int] = {}
        for table in self.tables_without_technical_dates():
            if only_physical_tables and not self.is_visible_physical_table(table):
                continue
            for partition in safe_list(table, "partitions"):
                source_type = display_source_type(self.detect_source_type(
                    safe_value(partition, "expression", ""),
                    safe_value(partition, "sourceType", ""),
                ))
                source_types[source_type] = source_types.get(source_type, 0) + 1

        self._cache[cache_key] = source_types
        return source_types

    def existing_columns_map(self) -> dict[str, dict[str, Any]]:
        if "existing_columns_map" in self._cache:
            return self._cache["existing_columns_map"]

        result: dict[str, dict[str, Any]] = {}
        for table in self.tables_without_technical_dates():
            table_name = safe_value(table, "name", "")
            table_key = normalize_text(table_name)
            result.setdefault(table_key, {"name": table_name, "columns": {}})
            for column in safe_list(table, "columns"):
                column_name = safe_value(column, "name", "")
                result[table_key]["columns"][normalize_text(column_name)] = column_name

        self._cache["existing_columns_map"] = result
        return result

    def columns_used_in_measures(self) -> set[tuple[str, str]]:
        if "columns_used_in_measures" in self._cache:
            return self._cache["columns_used_in_measures"]

        columns_map = self.existing_columns_map()
        used: set[tuple[str, str]] = set()
        patterns = [r"'([^']+)'\[([^\]]+)\]", r"\b([A-Za-z0-9_]+)\[([^\]]+)\]"]

        for measure in self.measures():
            expression = safe_text(measure.get("Expressao DAX", ""))
            for pattern in patterns:
                for table_ref, column_ref in re.findall(pattern, expression):
                    table_key = normalize_text(table_ref)
                    column_key = normalize_text(column_ref)
                    if table_key in columns_map and column_key in columns_map[table_key]["columns"]:
                        used.add((columns_map[table_key]["name"], columns_map[table_key]["columns"][column_key]))

        self._cache["columns_used_in_measures"] = used
        return used

    def summary(self) -> dict[str, Any]:
        source_types = self.count_source_types(only_physical_tables=True)
        visible_tables = self.visible_physical_tables()
        measures = self.measures()
        return {
            "Dashboard": safe_value(self.data, "dashboardName", "Nao informado"),
            "Modelo": safe_value(self.data, "modelName", "Nao informado"),
            "Data de exportacao": safe_value(self.data, "exportDate", "Nao informado"),
            "Cultura": safe_value(self.metadata, "culture", "Nao informado"),
            "Modo padrao": safe_value(self.metadata, "defaultMode", "Nao informado"),
            "Colunas utilizadas": self.count_visible_fields(visible_tables),
            "Colunas utilizadas em medidas": len(self.columns_used_in_measures()),
            "Colunas totais": self.count_total_columns(),
            "Medidas": len(measures),
            "Fontes de dados": len(source_types),
            "Tipos de fontes": ", ".join(source_types.keys()) if source_types else "Nao detectado",
            "Tabelas totais": len(self.tables_without_technical_dates()),
            "Relacionamentos": len(self.relationship_rows()),
        }

    def table_rows(self) -> list[dict[str, Any]]:
        return [
            {
                "Tabela": safe_value(table, "name", ""),
                "Tipo": translate_model_type(safe_value(table, "tableType", "")),
                "Oculta": "Sim" if safe_value(table, "isHidden", False) else "Nao",
                "Colunas": len(safe_list(table, "columns")),
                "Colunas visiveis": self.count_visible_fields([table]),
                "Medidas": len(safe_list(table, "measures")),
                "Particoes": len(safe_list(table, "partitions")),
                "Descricao": safe_value(table, "description", ""),
            }
            for table in self.tables_without_technical_dates()
        ]

    def column_rows(self) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for table in self.tables_without_technical_dates():
            table_name = safe_value(table, "name", "")
            for column in safe_list(table, "columns"):
                rows.append({
                    "Coluna": safe_value(column, "name", ""),
                    "Tabela": table_name,
                    "Tipo de dado": safe_value(column, "dataType", ""),
                    "Tipo de coluna": translate_model_type(safe_value(column, "columnType", "")),
                    "Oculto": "Sim" if safe_value(column, "isHidden", False) else "Nao",
                    "Formato": safe_value(column, "formatString", ""),
                    "Categoria": safe_value(column, "dataCategory", ""),
                    "Pasta": safe_value(column, "displayFolder", ""),
                    "Descricao": safe_value(column, "description", ""),
                })
        return rows

    def measures(self) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for table in self.tables_without_technical_dates():
            table_name = safe_value(table, "name", "")
            for measure in safe_list(table, "measures"):
                expression = safe_value(measure, "expression", "")
                rows.append({
                    "Medida": safe_value(measure, "name", ""),
                    "Tabela": table_name,
                    "Oculta": "Sim" if safe_value(measure, "isHidden", False) else "Nao",
                    "Formato": safe_value(measure, "formatString", ""),
                    "Pasta": safe_value(measure, "displayFolder", ""),
                    "Tamanho DAX": len(safe_text(expression)),
                    "Expressao DAX": expression,
                    "Descricao": safe_value(measure, "description", ""),
                })
        return rows

    def source_rows(self, only_physical_tables: bool = False) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for table in self.tables_without_technical_dates():
            if only_physical_tables and not self.is_visible_physical_table(table):
                continue
            table_name = safe_value(table, "name", "")
            for partition in safe_list(table, "partitions"):
                expression = safe_value(partition, "expression", "")
                server, database = detect_database_server(expression)
                detected_source_type = display_source_type(self.detect_source_type(
                    expression,
                    safe_value(partition, "sourceType", ""),
                ))
                rows.append({
                    "Tabela": table_name,
                    "Particao": safe_value(partition, "name", ""),
                    "Fonte detectada": detected_source_type,
                    "Tipo fonte": display_source_type(translate_model_type(safe_value(partition, "sourceType", ""))),
                    "Modo": translate_model_type(safe_value(partition, "mode", "")),
                    "Servidor": server,
                    "Banco": database,
                    "SQL detectado": detect_sql_in_m_expression(expression),
                    "Expressao M": expression,
                })
        return rows

    def relationship_rows(self) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for relationship in self.relationships:
            from_table = safe_value(relationship, "fromTable", "")
            to_table = safe_value(relationship, "toTable", "")
            if self.is_technical_date_table_name(from_table) or self.is_technical_date_table_name(to_table):
                continue
            rows.append({
                "Tabela origem": to_table,
                "Coluna origem": safe_value(relationship, "toColumn", ""),
                "Tabela destino": from_table,
                "Coluna destino": safe_value(relationship, "fromColumn", ""),
                "Cardinalidade origem": safe_value(relationship, "toCardinality", ""),
                "Cardinalidade destino": safe_value(relationship, "fromCardinality", ""),
                "Direcao filtro": safe_value(relationship, "crossFilteringBehavior", ""),
                "Ativo": "Sim" if safe_value(relationship, "isActive", True) else "Nao",
                "Relacionamento": safe_value(relationship, "name", ""),
            })
        return rows

    def full_report(self) -> dict[str, Any]:
        return {
            "summary": self.summary(),
            "tables": self.table_rows(),
            "columns": self.column_rows(),
            "measures": self.measures(),
            "sources": self.source_rows(),
            "relationships": self.relationship_rows(),
            "columnsUsedInMeasures": [
                {"Tabela": table, "Coluna": column}
                for table, column in sorted(self.columns_used_in_measures())
            ],
            "raw": {
                "dashboardName": safe_value(self.data, "dashboardName", ""),
                "modelName": safe_value(self.data, "modelName", ""),
                "exportDate": safe_value(self.data, "exportDate", ""),
            },
        }
