from typing import Any

from app.services.analyzer import PowerBIAnalyzer, safe_bool, safe_list, safe_text, safe_value
from app.ingestion.normalization import NORMALIZATION_KEY, UNKNOWN, relationship_endpoint_key


COLUMN_COMPARE_FIELDS = {
    "dataType": "tipo de dado",
    "columnType": "tipo de coluna",
    "isHidden": "visibilidade",
    "formatString": "formato",
    "description": "descrição",
}

RELATIONSHIP_COMPARE_FIELDS = {
    "fromCardinality": "cardinalidade destino",
    "toCardinality": "cardinalidade origem",
    "crossFilteringBehavior": "direção de filtro",
    "isActive": "ativo",
}


def compare_field_changes(
    before_item: dict[str, Any],
    after_item: dict[str, Any],
    fields: dict[str, str],
) -> list[dict[str, str]]:
    def comparison_value(item: dict[str, Any], field: str) -> Any:
        metadata = item.get(NORMALIZATION_KEY, {})
        if isinstance(metadata, dict):
            sources = metadata.get("fields", {})
            if isinstance(sources, dict) and sources.get(field) == "unknown":
                return None
            normalized = metadata.get("normalized", {})
            if isinstance(normalized, dict) and field in normalized:
                value = normalized[field]
                return None if value == UNKNOWN else value
        if field not in item or item.get(field) is None:
            return None
        return item.get(field, "")

    changes: list[dict[str, str]] = []
    for field, label in fields.items():
        before_value = comparison_value(before_item, field)
        after_value = comparison_value(after_item, field)
        if before_value is None or after_value is None:
            continue
        before_original = safe_text(before_item.get(field, "")).strip()
        after_original = safe_text(after_item.get(field, "")).strip()
        before = safe_text(before_value).strip()
        after = safe_text(after_value).strip()
        if before != after:
            changes.append({"campo": label, "antes": before_original, "depois": after_original})
    return changes


def _partition_value(partition: dict[str, Any], field: str) -> Any:
    metadata = partition.get(NORMALIZATION_KEY, {})
    if isinstance(metadata, dict):
        sources = metadata.get("fields", {})
        if isinstance(sources, dict) and sources.get(field) == "unknown":
            return None
        normalized = metadata.get("normalized", {})
        if isinstance(normalized, dict) and field in normalized:
            value = normalized[field]
            return None if value == UNKNOWN else value
    if field not in partition or partition.get(field) is None:
        return None
    if field == "expression":
        return partition.get("normalizedExpression", partition.get(field))
    return partition.get(field)


def _partition_changes(base_table: dict[str, Any], new_table: dict[str, Any]) -> tuple[list[str], list[str], list[str]]:
    base_partitions = {
        partition.get("name", ""): partition
        for partition in safe_list(base_table, "partitions")
        if partition.get("name", "")
    }
    new_partitions = {
        partition.get("name", ""): partition
        for partition in safe_list(new_table, "partitions")
        if partition.get("name", "")
    }
    base_names = set(base_partitions)
    new_names = set(new_partitions)
    added = sorted(new_names - base_names)
    removed = sorted(base_names - new_names)
    modified: list[str] = []
    compared_fields = ("sourceType", "mode", "expression")
    for name in sorted(base_names & new_names):
        has_known_difference = False
        for field in compared_fields:
            before = _partition_value(base_partitions[name], field)
            after = _partition_value(new_partitions[name], field)
            if before is not None and after is not None and before != after:
                has_known_difference = True
                break
        if has_known_difference:
            modified.append(name)
    return added, removed, modified


def compare_models(base_data: dict[str, Any], new_data: dict[str, Any]) -> dict[str, Any]:
    base_analyzer = PowerBIAnalyzer(base_data)
    new_analyzer = PowerBIAnalyzer(new_data)

    def valid_table(table: dict[str, Any], analyzer: PowerBIAnalyzer) -> bool:
        name = table.get("name", "")
        return (
            bool(name)
            and not analyzer.is_technical_date_table(table)
            and not safe_bool(safe_value(table, "isAutoGenerated", False))
        )

    def tables_by_name(data: dict[str, Any], analyzer: PowerBIAnalyzer) -> dict[str, dict[str, Any]]:
        return {
            table.get("name", ""): table
            for table in safe_list(data, "tables")
            if valid_table(table, analyzer)
        }

    base_tables = tables_by_name(base_data, base_analyzer)
    new_tables = tables_by_name(new_data, new_analyzer)
    base_names = set(base_tables)
    new_names = set(new_tables)

    result: dict[str, Any] = {
        "dashboard_base": safe_value(base_data, "dashboardName", "BASE"),
        "dashboard_novo": safe_value(new_data, "dashboardName", "NOVO"),
        "tabelas": {
            "adicionadas": sorted(new_names - base_names),
            "removidas": sorted(base_names - new_names),
            "modificadas": [],
        },
        "medidas": {"adicionadas": [], "removidas": [], "modificadas": []},
        "colunas": {"adicionadas": [], "removidas": [], "modificadas": []},
        "relacionamentos": {"adicionados": [], "removidos": [], "modificados": []},
    }

    for name in sorted(base_names & new_names):
        base_table = base_tables[name]
        new_table = new_tables[name]

        base_columns = {
            column.get("name", ""): column
            for column in safe_list(base_table, "columns")
            if column.get("name", "")
        }
        new_columns = {
            column.get("name", ""): column
            for column in safe_list(new_table, "columns")
            if column.get("name", "")
        }
        base_column_names = set(base_columns)
        new_column_names = set(new_columns)
        added_columns = sorted(new_column_names - base_column_names)
        removed_columns = sorted(base_column_names - new_column_names)
        modified_columns: list[str] = []

        for column in added_columns:
            result["colunas"]["adicionadas"].append({"tabela": name, "coluna": column})
        for column in removed_columns:
            result["colunas"]["removidas"].append({"tabela": name, "coluna": column})
        for column in sorted(base_column_names & new_column_names):
            changes = compare_field_changes(base_columns[column], new_columns[column], COLUMN_COMPARE_FIELDS)
            if changes:
                modified_columns.append(column)
                result["colunas"]["modificadas"].append({
                    "tabela": name,
                    "coluna": column,
                    "alterações": [f"{change['campo']}: {change['antes']} -> {change['depois']}" for change in changes],
                })

        base_measures = {
            measure.get("name", ""): measure
            for measure in safe_list(base_table, "measures")
            if measure.get("name", "")
        }
        new_measures = {
            measure.get("name", ""): measure
            for measure in safe_list(new_table, "measures")
            if measure.get("name", "")
        }
        base_measure_names = set(base_measures)
        new_measure_names = set(new_measures)
        added_measures = sorted(new_measure_names - base_measure_names)
        removed_measures = sorted(base_measure_names - new_measure_names)

        for measure in added_measures:
            result["medidas"]["adicionadas"].append({
                "tabela": name,
                "medida": measure,
                "expressao_dax": safe_text(new_measures[measure].get("expression", "")),
            })
        for measure in removed_measures:
            result["medidas"]["removidas"].append({
                "tabela": name,
                "medida": measure,
                "expressao_dax": safe_text(base_measures[measure].get("expression", "")),
            })

        modified_measures = []
        for measure in sorted(base_measure_names & new_measure_names):
            def normalized_expression(item: dict[str, Any]) -> str:
                metadata = item.get(NORMALIZATION_KEY, {})
                if isinstance(metadata, dict):
                    normalized = metadata.get("normalized", {})
                    if isinstance(normalized, dict) and "expression" in normalized:
                        return safe_text(normalized["expression"]).strip()
                return safe_text(item.get("normalizedExpression", item.get("expression", ""))).strip()

            before = normalized_expression(base_measures[measure])
            after = normalized_expression(new_measures[measure])
            if before != after:
                modified_measures.append(measure)
                result["medidas"]["modificadas"].append({
                    "tabela": name,
                    "medida": measure,
                    "antes": safe_text(base_measures[measure].get("expression", "")),
                    "depois": safe_text(new_measures[measure].get("expression", "")),
                })

        added_partitions, removed_partitions, modified_partitions = _partition_changes(base_table, new_table)

        if (
            added_columns or removed_columns or modified_columns
            or added_measures or removed_measures or modified_measures
            or added_partitions or removed_partitions or modified_partitions
        ):
            result["tabelas"]["modificadas"].append({
                "nome": name,
                "colunas_adicionadas": added_columns,
                "colunas_removidas": removed_columns,
                "colunas_modificadas": modified_columns,
                "medidas_adicionadas": added_measures,
                "medidas_removidas": removed_measures,
                "medidas_modificadas": modified_measures,
                "particoes_adicionadas": added_partitions,
                "particoes_removidas": removed_partitions,
                "particoes_modificadas": modified_partitions,
            })

    excluded_tables = set()
    for data, analyzer in ((base_data, base_analyzer), (new_data, new_analyzer)):
        for table in safe_list(data, "tables"):
            name = table.get("name", "")
            if analyzer.is_technical_date_table(table):
                excluded_tables.add(name)

    def relationship_key(relationship: dict[str, Any]) -> str:
        metadata = relationship.get(NORMALIZATION_KEY, {})
        if isinstance(metadata, dict) and metadata.get("relationshipKey"):
            return str(metadata["relationshipKey"])
        return relationship_endpoint_key(relationship)

    def relationship_display_key(relationship: dict[str, Any]) -> str:
        return (
            f"{relationship.get('fromTable', '')}.{relationship.get('fromColumn', '')} -> "
            f"{relationship.get('toTable', '')}.{relationship.get('toColumn', '')}"
        )

    def filtered_relationships(data: dict[str, Any]) -> dict[str, dict[str, Any]]:
        result: dict[str, dict[str, Any]] = {}
        for relationship in safe_list(data, "relationships"):
            if relationship.get("fromTable", "") in excluded_tables or relationship.get("toTable", "") in excluded_tables:
                continue
            key = relationship_key(relationship)
            if key in result:
                key = f"{key}|name:{safe_text(relationship.get('name', '')).casefold()}"
                suffix = 2
                while key in result:
                    key = f"{key}|ordinal:{suffix}"
                    suffix += 1
            result[key] = relationship
        return result

    base_relationships = filtered_relationships(base_data)
    new_relationships = filtered_relationships(new_data)
    result["relacionamentos"]["adicionados"] = sorted(
        relationship_display_key(new_relationships[key])
        for key in set(new_relationships) - set(base_relationships)
    )
    result["relacionamentos"]["removidos"] = sorted(
        relationship_display_key(base_relationships[key])
        for key in set(base_relationships) - set(new_relationships)
    )

    for relationship in sorted(set(base_relationships) & set(new_relationships)):
        changes = compare_field_changes(
            base_relationships[relationship],
            new_relationships[relationship],
            RELATIONSHIP_COMPARE_FIELDS,
        )
        if changes:
            result["relacionamentos"]["modificados"].append({
                "relacionamento": relationship_display_key(base_relationships[relationship]),
                "alterações": [f"{change['campo']}: {change['antes']} -> {change['depois']}" for change in changes],
            })

    return result
